name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      -       - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inspect GitHub OIDC claims
        run: |
          python3 - <<'PY'
          import os
          import json
          import base64
          import urllib.request

          url = os.environ["ACTIONS_ID_TOKEN_REQUEST_URL"] + "&audience=sts.amazonaws.com"

          request = urllib.request.Request(
              url,
              headers={
                  "Authorization": "bearer " + os.environ["ACTIONS_ID_TOKEN_REQUEST_TOKEN"]
              }
          )

          token = json.load(urllib.request.urlopen(request))["value"]

          payload = token.split(".")[1]
          payload += "=" * (-len(payload) % 4)

          claims = json.loads(base64.urlsafe_b64decode(payload))

          for key in [
              "sub",
              "aud",
              "repository",
              "repository_owner",
              "ref",
              "event_name"
          ]:
              print(f"{key}: {claims.get(key)}")
          PY

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::317287357336:role/GitHubActions-IAM-Governance
          aws-region: us-east-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan